version: '3'

services:
  
  service-biblioteca-backend:
    container_name: biblioteca-backend-app
    image: biblioteca-backend-app:latest
    build:
      context: ./biblioteca-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=docker
    networks:
      - network

  service-biblioteca-frontend:
    container_name: biblioteca-frontend-app
    image: biblioteca-frontend-app:latest
    build: 
        context: ./biblioteca-frontend
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./biblioteca-frontend/.env    
    command: npm run start    
    networks:
      - network      

networks:
  network: {}