spring:
  profiles:
    active: "@spring.profiles.active@"
  jpa:
    open-in-view: false

app:
  jwt:
    secret: "W%@VBrlgz#x@wfCwdk%2Gww^svc$AFBYskQ*H0m0ih@&igdNo*" #sequencia de caracteres para assinar token
    expiration: 120000 # 2minutos