spring:
  datasource:
    url: jdbc:h2:mem:localhost/crud
    username: sa
    password: 123456
  h2:
    console:
      enabled: true  
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show_sql: true
app:
  jwt:
    secret: "W%@VBrlgz#x@wfCwdk%2Gww^svc$AFBYskQ*H0m0ih@&igdNo*" #sequencia de caracteres para assinar token
    expiration: 120000 # 2minutos
  frontend-url: http://localhost:3000